export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST"
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS"
export const GET_CONVERSATION_FAIL = "GET_CONVERSATION_FAIL"

export const ADD_CONVERSATION_REQUEST = "ADD_CONVERSATION_REQUEST"
export const ADD_CONVERSATION_SUCCESS = "ADD_CONVERSATION_SUCCESS"
export const ADD_CONVERSATION_FAIL = "ADD_CONVERSATION_FAIL"

export const ADD_MESSAGE_REQUEST = "ADD_MESSAGE_REQUEST"
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS"
export const ADD_MESSAGE_FAIL = "ADD_MESSAGE_FAIL"

export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST"
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS"
export const GET_MESSAGE_FAIL = "GET_MESSAGE_FAIL"

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS"
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL"

export const GET_ONLINE_USERS = "GET_ONLINE_USERS"