export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL";

export const CLEAR_NOTIFICATION_REQUEST = "CLEAR_NOTIFICATION_REQUEST";
export const CLEAR_NOTIFICATION_SUCCESS = "CLEAR_NOTIFICATION_SUCCESS";
export const CLEAR_NOTIFICATION_FAIL = "CLEAR_NOTIFICATION_FAIL";

export const CLEAR_NOTIFICATION_STATE = "CLEAR_NOTIFICATION_STATE";