//FOR SELF ALL POSTS
export const GET_USER_ALL_POST_REQUEST = "GET_USER_ALL_POST_REQUEST";
export const GET_USER_ALL_POST_SUCCESS = "GET_USER_ALL_POST_SUCCESS";
export const GET_USER_ALL_POST_FAIL = "GET_USER_ALL_POST_FAIL";

export const GET_OTHERS_TIMELINE_POST_REQUEST = "GET_OTHERS_TIMELINE_POST_REQUEST";
export const GET_OTHERS_TIMELINE_POST_SUCCESS = "GET_OTHERS_TIMELINE_POST_SUCCESS";
export const GET_OTHERS_TIMELINE_POST_FAIL = "GET_OTHERS_TIMELINE_POST_FAIL";

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const CLEAR_POST_OPERATIONS = "CLEAR_POST_OPERATIONS";
export const CLEAR_POST_OPERATIONS_WITHOUT_POSTS = "CLEAR_POST_OPERATIONS_WITHOUT_POSTS";