
export const GET_SINGLE_USER_REQUEST = "GET_SINGLE_USER_REQUEST";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const GET_FRIENDLIST_REQUEST = "GET_FRIENDLIST_REQUEST";
export const GET_FRIENDLIST_SUCCESS = "GET_FRIENDLIST_SUCCESS";
export const GET_FRIENDLIST_FAIL = "GET_FRIENDLIST_FAIL";

export const FOLLOW_UNFOLLOW_REQUEST = "FOLLOW_UNFOLLOW_REQUEST";
export const FOLLOW_UNFOLLOW_SUCCESS = "FOLLOW_UNFOLLOW_SUCCESS";
export const FOLLOW_UNFOLLOW_FAIL = "FOLLOW_UNFOLLOW_FAIL";

export const CLEAR_FOLLOW_UNFOLLOW_FAIL = "CLEAR_FOLLOW_UNFOLLOW_FAIL";

